### PR TITLE
Fix gift badges 

### PR DESCRIPTION
**Pull request by ZePedroResende**

### CODE REVIEW

**Review by marcelo140 — APPROVED** [review]
`if not` = `unless`

**Comment by ZePedroResende** [comment]
@marcelo140 why :( ?

**Comment by marcelo140** [comment]
Oh, I just remembered something. Not sure but I think badge counting is cached and is not updated unless `reset_badge_counters` is called, which is something both these methods don't do.

**Comment by ZePedroResende** [comment]
@marcelo140 they are update , i checked :)

**Pull request merged**
